[project]
name = "enterprise-ai-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "fastembed>=0.7.4",
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]
[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
]
